- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
* Ginger changed from 670ff8c to 086765c:
```
086765c Update functionalities for Platform Management
30cefe3 UT implemented for the new features implemented.
fbd22ff Audit graph backend implemetation.
0fc004a Audit predefined rules backend implementation.
e093afb Updated docs and i18n.py for the new features implemented.
d4101d1 Backend code implemented to get list of system calls.
c1d2fd7 Audit report implementation from the backend.
630bfae Audit log implementation from the backend.
bdea605 Audit conf implemented in the backend.
1c528ad Modified audit rules code for comments and added new features.
fe4324f Issue #166 : nfs mount fails with 500
ee3d989 Backend Changes for Sensor Data Records for Platform Management
670ff8c [HostOS] Revert Introducing iSCSI implementation for Storage …
```
> Weekly build - September, 7th, 2016

- kernel/centOS/7.2/kernel.spec
- kernel/kernel.yaml
* c96cdd2 Update kernel package to 4.8.1-3
* 91c5d11 Rename Source0 to linux-source.tar.gz
* bbf9cb2 Remove trailing -0 from Source0 in kernel.spec
* 13702cb Remove trailing .1 from Release macro in kernel.spec
* 6343965 Replace pkgrelease by specrelease in kernel.spec
* 6077452 Move dist to specrelease in kernel.spec
* 3b25c01 Remove buildid from kernel.spec
* b0e87bf Remove ibm_release from kernel.spec
* 8c19155 Remove release_date from kernel.spec
* 805bc6c Remove release_spin from kernel.spec
* a358f02 Remove release_day from kernel.spec
* a6ade38 Remove release_week from kernel.spec
> Package numbering cleanup in kernel.spec

- sos/sos.yaml
It was powerkvm-v3.1.1 but now it's hostos-devel, even though they're have the
same HEAD right now.
> Use hostos-devel branch in sos

- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
Changed from powerkvm-v3.1.1 to hostos-devel branches and also updated the
commit ids, as the follow:
- ginger  from 'f9164a4' to 'fd044e5'
- gingerbase from '56913b3' to '8296bfa'
- kimchi from '71787ff' to 'f4934ca'
- wok from '5443d11' to '8d8db13'
According to comment
https://github.com/open-power-host-os/builds/issues/106#issuecomment-259210354
> Use branch hostos-devel for kimchi/ginger/wok family

- SLOF/SLOF.yaml
- build_dependencies/golang/golang.yaml
- build_dependencies/librtas/librtas.yaml
- crash/crash.yaml
- dependencies/libseccomp/libseccomp.yaml
- dependencies/libservicelog/libservicelog.yaml
- dependencies/libvpd/libvpd.yaml
- ginger/ginger.yaml
- gingerbase/gingerbase.yaml
- kernel/kernel.yaml
- kimchi/kimchi.yaml
- libvirt/libvirt.yaml
- linux-firmware/linux-firmware.yaml
- lsvpd/lsvpd.yaml
- noVNC/noVNC.yaml
- powerpc-utils/powerpc-utils.yaml
- ppc64-diag/ppc64-diag.yaml
- qemu/qemu.yaml
- servicelog/servicelog.yaml
- sos/sos.yaml
- systemtap/systemtap.yaml
- wok/wok.yaml
Some projects (e.g. kernel) might require more than 7 digits to identify
a commit SHA-1 uniquely.
This also makes all packages use the same format.
> Use full SHA-1 for commit IDs in YAML files

- README.rst
- docker-swarm/centOS/7.2/docker-swarm.spec
- docker-swarm/centOS/7.2/rpmmacro
- docker-swarm/docker-swarm.yaml
Debug info RPM is not being built.
Spec file based on openSUSE:
https://build.opensuse.org/package/view_file/Virtualization:containers/docker-swarm/docker-swarm.spec
> Add docker-swarm package

- docker-swarm/centOS/7.2/rpmmacro
I made a mistake in PR #56 and used the wrong syntax in the rpmmacro file:
%define debug_package %{nil}
the correct doesn't use define piece (which is used hardcoded in the spec for
instance):
%debug_package %{nil}
> Fix docker-swarm build

- lshw/centOS/7.2/SOURCES/lshw-gui
- lshw/centOS/7.2/SOURCES/lshw.desktop
- lshw/centOS/7.2/SOURCES/org.ezix.lshw.gui.policy
- lshw/centOS/7.2/lshw.spec
- lshw/lshw.yaml
This builds the upstream development branch (based on B.02.18) which:
- adds pseries guest information
- adds machine description for PowerNV and pseries LPAR platform
- fixes motherboard model reporting for Power systems
- fixes physical ID information for CPU nodes
- adds Vital Product Data information for FSP and BMC based Power
systems
- updates CPU information for Power systems
> Add lshw package

- ppc64-diag/centOS/7.2/SOURCES/ppc64-diag-2.4.3-scriptlocation.patch
- ppc64-diag/centOS/7.2/ppc64-diag.spec
- ppc64-diag/ppc64-diag.yaml
Right now the ppc64-diag yaml was tied to an source tarball with 2.7.1 version
on its name. Removing this also requires to change the name of the expected
Source0 file in its spec.
Also adjustment is necessary in /ppc64-diag-2.4.3-scriptlocation.patch to make
it apply in the current repository state
> Adjust ppc64-diag yaml and spec to be flexible to version changes

- qemu/centOS/7.2/qemu.spec
With CentOS 7.3.1611, we now have the package qemu-kvm-ev in the
extras repo. Its spec file contains an "Obsoletes < 15:0-0" clause, so
we need to bump the epoch of our qemu-kvm package so that it takes
precedence.
> Increase qemu-kvm epoch to avoid obsolescence by qemu-kvm-ev

- docker/centOS/7/docker.spec
- flannel/centOS/7/flannel.spec
- gcc/centOS/7/gcc.spec
- golang-github-russross-blackfriday/centOS/7/golang-github-russross-blackfriday.spec
- golang-github-shurcooL-sanitized_anchor_name/centOS/7/golang-github-shurcooL-sanitized_anchor_name.spec
- golang/centOS/7/golang.spec
- kubernetes/centOS/7/kubernetes.spec
- libseccomp/centOS/7/libseccomp.spec
- libvirt/centOS/7/libvirt.spec
- oci-register-machine/centOS/7/oci-register-machine.spec
In order to run tests (under %check at spec files) we need to add "--with tests", i.e.  at config.yaml, mock-args "--with tests".  The tests are disabled by default. Changes applied to spec files with %check phase defined. Original behaviour preserved.
Refer to https://github.com/open-power-host-os/versions/pull/75 for more details.
> Make possible to skip tests (check phase)

- kubernetes/kubernetes.yaml
The kubernetes package main source is downloaded from an URL source,
whose "archive" attribute is currently not used. The build scripts will
be modified to use this attribute, and so it needs to be fixed to be
consistent with git's and hg's "archive" attribute, by removing the file
extension.
> Fix kubernetes archive name

- servicelog/centOS/7/servicelog.spec
Servicelog is one of the key components of HostOS so we always want
our version to take precedence over the distro's.
> Bump servicelog release

- systemtap/centOS/7/systemtap.spec
Since we use a more recent kernel than CentOS and the distro's
systemtap version doesn't have support for it, we need our package to
take precedence.
> Bump systemtap release

- lshw/centOS/7/lshw.spec
The commit used is ahead of the version tag in the Git repository, so
its better to specify it.
> Add Git commit ID to lshw release field

- docker/centOS/7/docker.spec
- docker/docker.yaml
- kubernetes/centOS/7/kubernetes.spec
- kubernetes/kubernetes.yaml
Change the docker and kubernetes packages yaml files to use the new sources format, with a main git source and multiple url sources.
> Set multiple sources for docker and kubernetes

- SLOF/CentOS/7/SLOF.spec
- crash/CentOS/7/crash.spec
- docker-swarm/CentOS/7/docker-swarm.spec
- flannel/CentOS/7/flannel.spec
- gcc/CentOS/7/gcc.spec
- ginger-base/CentOS/7/ginger-base.spec
- ginger/CentOS/7/ginger.spec
- golang-github-russross-blackfriday/CentOS/7/golang-github-russross-blackfriday.spec
- golang-github-shurcooL-sanitized_anchor_name/CentOS/7/golang-github-shurcooL-sanitized_anchor_name.spec
- hwdata/CentOS/7/hwdata.spec
- kernel/CentOS/7/kernel.spec
- kimchi/CentOS/7/kimchi.spec
- librtas/CentOS/7/librtas.spec
- libservicelog/CentOS/7/libservicelog.spec
- libvirt/CentOS/7/libvirt.spec
- libvpd/CentOS/7/libvpd.spec
- lshw/CentOS/7/lshw.spec
- lsvpd/CentOS/7/lsvpd.spec
- novnc/CentOS/7/novnc.spec
- ppc64-diag/CentOS/7/ppc64-diag.spec
- qemu/CentOS/7/qemu.spec
- servicelog/CentOS/7/servicelog.spec
- sos/CentOS/7/sos.spec
- wok/CentOS/7/wok.spec
As agreed with the team, we only do this when the used commit ID
is not in a release branch or associated with a release tag.
> Add git/mercurial/svn commit ID to RPM release number

- golang-github-russross-blackfriday/golang-github-russross-blackfriday.yaml
- golang-github-shurcooL-sanitized_anchor_name/golang-github-shurcooL-sanitized_anchor_name.yaml
- lsvpd/lsvpd.yaml
- servicelog/servicelog.yaml
Current naming is confusing because we also have build dependencies.
New name makes clearer the difference between both.
> Rename dependencies attribute to install_dependencies

- SLOF/CentOS/7/SLOF.spec
- SLOF/SLOF.yaml
And update to upstream slof available in qemu-2.8
Signed-off-by: Nikunj A Dadhania <nikunj@linux.vnet.ibm.com>
> Use hostos-devel branch for slof

- SLOF/CentOS/7/SLOF.spec
- crash/CentOS/7/crash.spec
- docker-swarm/CentOS/7/docker-swarm.spec
- flannel/CentOS/7/flannel.spec
- ginger-base/CentOS/7/ginger-base.spec
- ginger/CentOS/7/ginger.spec
- golang-github-russross-blackfriday/CentOS/7/golang-github-russross-blackfriday.spec
- hwdata/CentOS/7/hwdata.spec
- kernel/CentOS/7/kernel.spec
- kimchi/CentOS/7/kimchi.spec
- librtas/CentOS/7/librtas.spec
- libservicelog/CentOS/7/libservicelog.spec
- libvirt/CentOS/7/libvirt.spec
- libvpd/CentOS/7/libvpd.spec
- lshw/CentOS/7/lshw.spec
- lsvpd/CentOS/7/lsvpd.spec
- novnc/CentOS/7/novnc.spec
- ppc64-diag/CentOS/7/ppc64-diag.spec
- qemu/CentOS/7/qemu.spec
- qemu/qemu.yaml
- servicelog/CentOS/7/servicelog.spec
- sos/CentOS/7/sos.spec
- wok/CentOS/7/wok.spec
qemu had to be manually updated because its Makefile is not generating some doc files anymore.
The upgrade-versions script was incorrectly updating the release field when the package version was upgraded.
> Fix specs to allow automatic version upgrade

- libnl3/CentOS/7/libnl3.spec
The release number needs to be higher than CentOS for the package to be
installed.
> Bump libnl3 release

- golang-github-russross-blackfriday/CentOS/7/golang-github-russross-blackfriday.spec
- golang-github-shurcooL-sanitized_anchor_name/CentOS/7/golang-github-shurcooL-sanitized_anchor_name.spec
The packages golang-github-russross-blackfriday and
golang-github-shurcooL-sanitized_anchor_name need to provide a main
package and also a release bump to work with our idea of a Host OS release
package.
> Prepare golang-github-* packages for release package requirements

- servicelog/servicelog.yaml
According to the servicelog rpm spec, libservicelog is a build
requirement, not an installation requirement. libservicelog
already exists in base distribution (CentOS), but we want to
use the customized version provided by OP Host OS, so we must
mention it explicitly in servicelog yaml.
> Make libservicelog a build dependency of servicelog

- lsvpd/lsvpd.yaml
According to the lsvpd rpm spec, libvpd is a build
requirement, not an installation requirement. libvpd
already exists in base distribution (CentOS), but we want to
use the customized version provided by OP Host OS, so we must
mention it explicitly in servicelog yaml.
> Make libvpd a build dependency of lsvpd

- open-power-host-os/CentOS/7/open-power-host-os.spec
- open-power-host-os/open-power-host-os.yaml
The OpenPOWER Host OS metapackages are divided into:
- open-power-host-os-release: install release file, with Host OS version
- open-power-host-os-all: install all Host OS packages
- open-power-host-os-*: install selected package group
All of the remaining open-power-host-os-* RPMs require the corresponding versions of the release RPM, so the user is able to link the metapackages installed with a Host OS version. They also install specific versions of the Host OS packages, but allow them to be overridden with custom versions after the installation.
> Add support to build Host OS metapackages

- SLOF/CentOS/7/SLOF.spec
- crash/CentOS/7/crash.spec
- docker-swarm/CentOS/7/docker-swarm.spec
- docker/CentOS/7/docker.spec
- flannel/CentOS/7/flannel.spec
- gcc/CentOS/7/gcc.spec
- ginger-base/CentOS/7/ginger-base.spec
- ginger/CentOS/7/ginger.spec
- golang-github-russross-blackfriday/CentOS/7/golang-github-russross-blackfriday.spec
- golang-github-shurcooL-sanitized_anchor_name/CentOS/7/golang-github-shurcooL-sanitized_anchor_name.spec
- hwdata/CentOS/7/hwdata.spec
- kernel/CentOS/7/kernel.spec
- kimchi/CentOS/7/kimchi.spec
- kubernetes/CentOS/7/kubernetes.spec
- librtas/CentOS/7/librtas.spec
- libservicelog/CentOS/7/libservicelog.spec
- libvirt/CentOS/7/libvirt.spec
- libvpd/CentOS/7/libvpd.spec
- lshw/CentOS/7/lshw.spec
- lsvpd/CentOS/7/lsvpd.spec
- novnc/CentOS/7/novnc.spec
- ppc64-diag/CentOS/7/ppc64-diag.spec
- qemu/CentOS/7/qemu.spec
- servicelog/CentOS/7/servicelog.spec
- sos/CentOS/7/sos.spec
- wok/CentOS/7/wok.spec
Depends on https://github.com/open-power-host-os/builds/pull/224
The commit IDs are now only in YAML files.
> Remove hardcoded commits from spec files

- hwdata/CentOS/7/hwdata.spec
Currently, this package does not have an available git repository and
so it's commit ID is not in the YAML file.
Regression introduced in commit 5b8a44fc3baaf5969c084ac6c5c6a564ec5c55b1
> Revert hwdata's commit ID in spec file

- open-power-host-os/CentOS/7/SOURCES/90-open-power-host-os-default.preset
- open-power-host-os/CentOS/7/SOURCES/open-power-host-os-smt.service
- open-power-host-os/CentOS/7/open-power-host-os.spec
Depends on open-power-host-os/builds#202
The open-power-host-os-release package will contain a systemd service
and shell script to toggle SMT functionality.
Addresses issue open-power-host-os/builds/issues/16
> Add systemd service to disable SMT

- VERSION
Reverts open-power-host-os/versions#156
The update should have been done to beta. My apologies.
> Revert "Update Host OS version to 2.0"

- open-power-host-os/CentOS/7/SOURCES/hostos-openvswitch.te
- open-power-host-os/CentOS/7/open-power-host-os.spec
This change adds a new selinux policy named `hostos-openvswitch` that
allows openvswitch to create generic netlink sockets.
Fixes https://github.com/open-power-host-os/builds/issues/226
> Add openvswitch selinux policy (#226)

- open-power-host-os/CentOS/7/open-power-host-os.spec
Fix open-power-host-os-release dependencies for SELinux
The `Requires(post): policycoreutils` guarantees that `semodule`
command is available during postinstall.  However, to load an SELinux
policy in the ISO install time, the chrooted system also needs
selinux-policy, selinux-policy-targeted, and coreutils packages.
Adding them as %pre dependencies guarantees SELinux will be all set
when open-power-host-os-release is installed.
Fixes https://github.com/open-power-host-os/builds/issues/226
> Fix open-power-host-os-release dependencies for SELinux

- gcc/CentOS/7/gcc.spec
- gcc/gcc.yaml
Depends on https://github.com/open-power-host-os/builds/pull/241
It is not rare that builds got stuck at svn checkout.  From time to
time, the svn checkout from gcc.gnu.org terminates with error:
$ svn checkout svn://gcc.gnu.org/svn/gcc/branches/redhat/gcc-4_8-branch@240558 gcc-4_8-branch
svn: E210002: Unable to connect to a repository at URL 'svn://gcc.gnu.org/svn/gcc/branches/redhat/gcc-4_8-branch'
svn: E210002: Network connection closed unexpectedly
This patch configures gcc.yaml to download code from a gcc copy placed
at GitHub under open-power-host-os organization.  Hopefully, builds
will not get stuck at code checkout anymore.
> Use gcc copy from open-power-host-os organization at GitHub

- docker/centOS/7.2/docker.spec
The repository https://github.com/projectatomic/docker-storage-setup was renamed
to container-storage-setup, making the previous url of the tarball to download a
tarball containing the new directory name `container-storage-setup-<commitid>/`
in it.
We need to update docker.spec to reflect this modification, which happened after
tag v1.0.0 was created.
> docker.spec: Fix container-storage-setup directory name

- Jenkinsfile
The previous branch "pipeline" was only temporary.
> Checkout from master branch in Jenkinsfile

- qemu/CentOS/7/qemu.spec
- qemu/CentOS/7/rpmmacro
There were some unpacked qemu files:
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/qemu-2.9.0-1.gitc7bd488.el7.centos.ppc64le
warning: Installed (but unpackaged) file(s) found:
/usr/share/doc/qemu/qemu-doc.txt
/usr/share/doc/qemu/qemu-ga-ref.html
/usr/share/doc/qemu/qemu-ga-ref.txt
/usr/share/doc/qemu/qemu-qmp-ref.html
/usr/share/doc/qemu/qemu-qmp-ref.txt
/usr/share/man/man7/qemu-ga-ref.7.gz
/usr/share/man/man7/qemu-qmp-ref.7.gz
/usr/share/qemu/efi-e1000e.rom
/usr/share/qemu/efi-vmxnet3.rom
/usr/share/qemu/linuxboot_dma.bin
/usr/share/qemu/skiboot.lid
This commit fixes it and pack all these unpacked files.
> Pack unpacked qemu files

- kernel/CentOS/7/kernel.spec
- kernel/CentOS/7/rpmmacro
The perf documentation was generated regardless the macro with_doc so I just removed the verification for with_doc macro and listed unpacked files properly for perf package.
> Pack unpacked kernel files

- kernel/CentOS/7/kernel.spec
The following upstream commit renamed
arch/powerpc/{scripts -> tools}/gcc-check-mprofile-kernel.sh:
commit b71c9ffb140556004caf7ba27083f9d90ae8d14b
Author: Nicholas Piggin <npiggin@gmail.com>
Date:   Sat Nov 26 14:26:10 2016 +1100
powerpc: Add arch/powerpc/tools directory
This fixes the path in kernel.spec.
> kernel.spec: Fix gcc-check-mprofile-kernel.sh path

- VERSION
The development branch will no longer change milestones over time.
It will keep a constant "dev" milestone to differentiate from release
builds.
> Change milestone to "dev"

- qemu/CentOS/7/qemu.spec
- qemu/qemu.yaml
Update qemu.yaml to version 2.10.0 from hostos-devel branch and update qemu.spec
to solve the following packaging issues due to the update:
error: Installed (but unpackaged) file(s) found:
/usr/share/qemu/qemu_vga.ndrv
/usr/share/qemu/s390-netboot.img
File listed twice: /etc/qemu
File listed twice: /etc/qemu/bridge.conf
Installed (but unpackaged) file(s) found:
/usr/share/qemu/qemu_vga.ndrv
/usr/share/qemu/s390-netboot.img
> Update to qemu 2.10.0

- open-power-host-os/CentOS/7/open-power-host-os.spec
- qemu/CentOS/7/qemu.spec
- qemu/qemu.yaml
These two commits come from hostos-devel and are required to build qemu 2.10 from hostos-release.
> qemu 2.10 backports for hostos-release

- open-power-host-os/CentOS/7/open-power-host-os.spec
- qemu/CentOS/7/qemu.spec
Last change to the qemu spec file did not update the spec file release or the metapackage dependencies.
> Fix qemu release in open-power-host-os package

- open-power-host-os/CentOS/7/open-power-host-os.spec
- qemu/CentOS/7/qemu.spec
The skiboot.lid file is provided by the opal-firmware package. It doesn't need to be present in the qemu installation.
Since we now provide the opal-firmware package, that file was in conflict between the two packages.
Fixes open-power-host-os/builds#307
> Remove skiboot.lid from qemu package
