- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- qemu/centOS/7.2/qemu.spec
- qemu/qemu.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
Fix open-power-host-os/builds#80
> Weekly build 28/09/2016

- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- libvirt/centOS/7.2/libvirt.spec
- libvirt/libvirt.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
Fix open-power-host-os/builds#86
> Weekly build 05/10/2016

- ginger/centOS/7.2/ginger.spec
- gingerbase/centOS/7.2/gingerbase.spec
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- wok/centOS/7.2/wok.spec
The versions were not in sync with upstream repository.
Also updated kimchi commit ID.
> Update kimchi, wok, ginger and gingerbase versions

- kernel/centOS/7.2/kernel.spec
- kernel/kernel.yaml
The actual kernel version is 4.8.1, not 4.8.0.
> Fix kernel version in kernel.spec

- dependencies/libservicelog/centOS/7.2/SOURCES/libservicelog-1.1.15-libs.patch
- dependencies/libservicelog/centOS/7.2/libservicelog.spec
- dependencies/libservicelog/libservicelog.yaml
- servicelog/centOS/7.2/servicelog.spec
- servicelog/servicelog.yaml
Libservicelog:
project: open-power-host-os/libservicelog 
Branch: hostos-devel
Servicelog:
project: open-power-host-os/servicelog 
Branch: hostos-devel
Fixes and Closes open-power-host-os/builds#11
> Add libservicelog and servicelog

- qemu/centOS/7.2/qemu.spec
- qemu/qemu.yaml
This will not be necessary when we got the version automatically, til there such fix are necessary bad thing.
> Update qemu version to 2.7.0

- ginger/ginger.yaml
- gingerbase/gingerbase.yaml
- kimchi/kimchi.yaml
- wok/wok.yaml
* Updating package ginger from 3c049fb to 1e3aaec
* Updating package gingerbase from 2bc859f to 0f9bf86
* Updating package wok from bd24776 to 680eb9f
* Updating package kimchi from 51d423e to 19b3621
Closes open-power-host-os/builds#94
> Weekly build October, 19th, 2016

- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kernel/centOS/7.2/kernel.spec
- kernel/kernel.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- qemu/centOS/7.2/qemu.spec
- qemu/qemu.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
Updating package kernel from a3a03f3 to 888abf4
Updating package ginger from 1e3aaec to ed6b5cc
Updating package gingerbase from 0f9bf86 to a025aae
Updating package wok from 680eb9f to 50065e0
Updating package kimchi from 19b3621 to 0c5755c
Updating package QEMU from 1b11fa6 to 4f0198b
Closes open-power-host-os/builds#101
> Weekly build October, 26th 2016

- ginger/centOS/7.2/ginger.spec
- ginger/ginger.yaml
- gingerbase/centOS/7.2/gingerbase.spec
- gingerbase/gingerbase.yaml
- kimchi/centOS/7.2/kimchi.spec
- kimchi/kimchi.yaml
- wok/centOS/7.2/wok.spec
- wok/wok.yaml
Closes open-power-host-os/builds#103
Updating package open-power-host-os/ginger ed6b5cc to f9164a4
Updating package open-power-host-os/gingerbase from a025aae to 56913b3
Updating package open-power-host-os/wok from 50065e0 to 5443d11
Updating package open-power-host-os/kimchi from 0c5755c to 71787ff
> Weekly Build, November, 2nd, 2016

- SLOF/SLOF.yaml
- SLOF/centOS/7.2/SLOF.spec
- build_dependencies/librtas/centOS/7.2/librtas.spec
- dependencies/libvpd/centOS/7.2/libvpd.spec
- ginger/centOS/7.2/ginger.spec
- gingerbase/centOS/7.2/gingerbase.spec
- iprutils/centOS/7.2/iprutils.spec
- kernel/centOS/7.2/kernel.spec
- kimchi/centOS/7.2/kimchi.spec
- lsvpd/centOS/7.2/lsvpd.spec
- noVNC/centOS/7.2/noVNC.spec
- qemu/centOS/7.2/qemu.spec
- qemu/qemu.yaml
- sos/centOS/7.2/sos.spec
- wok/centOS/7.2/wok.spec
Spec cleanup for:
- qemu
- sos
- slof
- kimchi/ginger/ginger-base/wok
- librtas
- iprutils
- lsvpd and libvpd
- linux kernel
> Specs cleanup patch series

- README.rst
- flannel/centOS/7.2/SOURCES/change-4001-to-2379-in-help-and-README.patch
- flannel/centOS/7.2/SOURCES/change-coreos.com-network-to-atomic.io-network-in-he.patch
- flannel/centOS/7.2/SOURCES/flannel-docker.conf
- flannel/centOS/7.2/SOURCES/flannel-tmpfiles.conf
- flannel/centOS/7.2/SOURCES/flanneld.service
- flannel/centOS/7.2/SOURCES/flanneld.sysconf
- flannel/centOS/7.2/SOURCES/internal-to-inteernal.patch
- flannel/centOS/7.2/flannel.spec
- flannel/flannel.yaml
Spec file based on CentOS 7.2 extras repository:
https://git.centos.org/blob/rpms!flannel/7e924c9cf84caaf230f6a50c2a5ad5b0b6d93a9a/SPECS!flannel.spec
> Add flannel package

- README.rst
- hwdata/centOS/7.2/hwdata.spec
- hwdata/hwdata.yaml
Based on spec file from CentOS:
https://git.centos.org/blob/rpms!hwdata.git/27a8460fd65b1ed640af6cd740095f6833b59b30/SPECS!hwdata.spec%3Bjsessionid=1m8f5qug2497f1xa0jqwyw1j8l
> Add hwdata package

- libservicelog/libservicelog.yaml
- libvpd/libvpd.yaml
- lsvpd/lsvpd.yaml
- ppc64-diag/ppc64-diag.yaml
- servicelog/servicelog.yaml
All package repositories under the organization should be kept up-to-date.
> Add support to update remaining open-power-host-os packages

- kubernetes/centOS/7.2/SOURCES/0001-internal-inteernal.patch
- kubernetes/centOS/7.2/SOURCES/Change-etcd-server-port.patch
- kubernetes/centOS/7.2/SOURCES/build-with-debug-info.patch
- kubernetes/centOS/7.2/SOURCES/disable-v1beta3.patch
- kubernetes/centOS/7.2/SOURCES/fix-support-for-ppc64le.patch
- kubernetes/centOS/7.2/SOURCES/genmanpages.sh
- kubernetes/centOS/7.2/SOURCES/hack-test-cmd.sh.patch
- kubernetes/centOS/7.2/SOURCES/hyperkube-kubectl-dont-shift-os.Args.patch
- kubernetes/centOS/7.2/SOURCES/hyperkube.server-don-t-parse-args-for-any-command.patch
- kubernetes/centOS/7.2/SOURCES/internal-to-inteernal.patch
- kubernetes/centOS/7.2/SOURCES/remove-apiserver-add-kube-prefix-for-hyperkube.patch
- kubernetes/centOS/7.2/kubernetes.spec
- kubernetes/kubernetes.yaml
Based on CentOS7.2 extras:
https://git.centos.org/tree/rpms!kubernetes/55f026501156d8d0b37c258352cdc4f608d13eff/SPECS
> Add Kubernetes to HostOS

- libnl3/centOS/7/SOURCES/0001-compare-v4-addr-rh1370503.patch
- libnl3/centOS/7/SOURCES/ibm-bug-81413-libnltest.patch
- libnl3/centOS/7/libnl3.spec
- libnl3/libnl3.yaml
RPM specification file obtained from libnl3 source rpm
in CentOS 7.3.1611.
> Add libnl3 package

- ginger/centOS/7/ginger.spec
Signed-off-by: Lucio Correia <luciojhc@linux.vnet.ibm.com>
> Update ginger spec to latest upstream version

- wok/CentOS/7/wok.spec
- wok/wok.yaml
Signed-off-by: Lucio Correia <luciojhc@linux.vnet.ibm.com>
> Synchronize wok spec with latest upstream changes

- wok/CentOS/7/wok.spec
Add missing dependency openssl.
> Fix error on spec

- wok/CentOS/7/wok.spec
It should have been bumped in commit
d164401dbb7c1a7878a43f105dc93e14d7e2bbac
> Bump wok release

- SLOF/SLOF.yaml
- crash/crash.yaml
- docker-swarm/docker-swarm.yaml
- docker/docker.yaml
- flannel/flannel.yaml
- ginger-base/ginger-base.yaml
- ginger/ginger.yaml
- golang-github-shurcooL-sanitized_anchor_name/golang-github-shurcooL-sanitized_anchor_name.yaml
- golang/golang.yaml
- hwdata/hwdata.yaml
- kernel/kernel.yaml
- kimchi/kimchi.yaml
- kubernetes/kubernetes.yaml
- librtas/librtas.yaml
- libservicelog/libservicelog.yaml
- libvirt/libvirt.yaml
- libvpd/libvpd.yaml
- lshw/lshw.yaml
- lsvpd/lsvpd.yaml
- novnc/novnc.yaml
- ppc64-diag/ppc64-diag.yaml
- qemu/qemu.yaml
- servicelog/servicelog.yaml
- sos/sos.yaml
- wok/wok.yaml
- Make indentation consistent
- Remove trailing whitespaces
> Make package metadata (yaml) files compliant with yamllint

- README.md
And mention the creation of presets and disabling of SMT.
> Create a section for the release package

- docker/centOS/7.2/docker.spec
- hwdata/hwdata.yaml
Some repositories are gone or were renamed. This updates packages metadata to new locations and fixes minor build issues.
> Fix build of legacy packages 1.0 and 1.5

- gcc/CentOS/7/gcc.spec
This pull packs unpacked gcc files and bump its release.
Fixes https://github.com/open-power-host-os/builds/issues/56
> Pack unpacked gcc files

- SLOF/CentOS/7/SLOF.spec
- SLOF/SLOF.yaml
> Update SLOF to 20170303-3.gitc39657a

- open-power-host-os/CentOS/7/open-power-host-os.spec
The package was updated, but the metapackage reference was not.
> Update open-power-host-os requirement of SLOF

- libvirt/CentOS/7/libvirt.spec
- libvirt/libvirt.yaml
- open-power-host-os/CentOS/7/open-power-host-os.spec
Update spec file based on the upstream one at
https://github.com/open-power-host-os/libvirt/blob/9af764e86aef7dfb0191a9561bf1d1abf941da05/libvirt.spec.in
> Update libvirt version to 3.6.0

- open-power-host-os/CentOS/7/open-power-host-os.spec
- servicelog/CentOS/7/servicelog.spec
- servicelog/servicelog.yaml
Based on spec file from
https://github.com/open-power-host-os/servicelog/blob/3955e8580ccad12de717b659f7d1c2aa2e05d6e5/servicelog.spec.in
> Update servicelog spec

- open-power-host-os/CentOS/7/open-power-host-os.spec
- servicelog/CentOS/7/servicelog.spec
It had been previously changed, but was missing a bump to be updateable.
> Bump servicelog spec file

- qemu/CentOS/7/SOURCES/95-kvm-ppc64-memlock.conf
- qemu/CentOS/7/qemu.spec
https://bugzilla.redhat.com/show_bug.cgi?id=1293024
Fixes: https://github.com/open-power-host-os/qemu/issues/3
> Raise the memory locking limit for non-privileged users

- libvpd/CentOS/7/libvpd.spec
- libvpd/libvpd.yaml
- open-power-host-os/CentOS/7/open-power-host-os.spec
Remove /var/lib/lsvpd/run.vpdupdate from files section, based on
https://github.com/open-power-host-os/libvpd/commit/7d959c5ff48978853b01c43e959236988a46a018
> Update libvpd spec

- libvirt/CentOS/7/libvirt.spec
- libvirt/libvirt.yaml
- open-power-host-os/CentOS/7/open-power-host-os.spec
Update libvirt to v3.9.0 and adjust libvirt.spec accordingly.
> Update libvirt to v3.9.0

- opal-prd/CentOS/7/opal-prd.spec
- opal-prd/opal-prd.yaml
- open-power-host-os/CentOS/7/open-power-host-os.spec
Fixes open-power-host-os/builds#306
> Add opal-prd

- open-power-host-os/CentOS/7/open-power-host-os.spec
- open-power-host-os/open-power-host-os.yaml
This should have been done in: "d5bf683 Add OPAL runtime services
packages"
> Add opal-prd dependency to metapackage

- open-power-host-os/CentOS/7/open-power-host-os.spec
- qemu/CentOS/7/qemu.spec
Fixes for the QEMU build after the latest update.
> Qemu build fixes
